name: Build & Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build-site:
    #runs-on: eagledata/jigsaw-docker:latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Build website
    #  run: jigsaw build production
    #- name: Move to public directory
    #  run: mv build_production/ public/
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Build production
        run: vendor/bin/jigsaw build production
      #- name: Install NPM Dependencies
      #  run: npm install
      #- name: Build Site
      #  run: npm run production
      #- name: Stage Files
      #  run: git add -f build_production
      
      - name: Stage Files
        run: git add -f build_production
      - name: Commit files
        run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         git commit -m "Build for deploy"
      - name: Publish
        run: |
         git subtree split --prefix build_production -b gh-pages
         git push -f origin gh-pages:gh-pages
         git branch -D gh-pages
