name: Build & Publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build-site:
    runs-on: eagledata/jigsaw-docker:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build website
      run: jigsaw build production
    - name: Move to public directory
      run: mv build_production/ public/
      
    #- name: Stage Files
    #  run: git add -f build_production
    #- name: Commit files
    #  run: |
    #    git config --local user.email "actions@github.com"
    #    git config --local user.name "GitHub Actions"
    #    git commit -m "Build for deploy"
    #- name: Publish
    #  run: |
    #    git subtree split --prefix build_production -b master
    #    git push -f origin master:master
    #    git branch -D master
